module.exports = {
  root: "/loyalty",
  summary: "/summary",
  progression: "/progression",
  claimReward: "/claim-reward",
  claimSeasonTierReward: "/seasons/:seasonId/tiers/:tierId/claim",
  admin: {
    tiers: "/admin/tiers",
    tiersDetail: "/admin/tiers/:id",
    seasons: "/admin/seasons",
    seasonsDetail: "/admin/seasons/:id",
    seasonsActivate: "/admin/seasons/:id/activate",
    seasonsDeactivate: "/admin/seasons/:id/deactivate",
    seasonSummary: "/admin/season-summary",
    tierConfigurations: "/admin/tier-configurations",
    tierConfigurationsDetail: "/admin/tier-configurations/:id",
    tierConfigurationHistory: "/admin/tier-configurations/:id/history",
    configAuditLogs: "/admin/config-audit-logs",
    configAuditLogDetail: "/admin/config-audit-logs/:id",
  },
};
