const express = require("express");
const appRoutes = require("../modules/app/app.routes");
const commonRoutes = require("../modules/common/common.routes");
const userRoutes = require("../modules/user/user.routes");
const adminRoutes = require("../modules/admin/admin.routes");
const productRoutes = require("../modules/products/product.routes");
const rewardRoutes = require("../modules/rewards/rewards.routes");
const redeemRoutes = require("../modules/redeems/redeems.routes");
const transactionRoutes = require("../modules/transactions/transactions.routes");
const appPaths = require("../modules/app/app.paths");
const commonPaths = require("../modules/common/common.paths");
const adminPaths = require("../modules/admin/admin.paths");
const userPaths = require("../modules/user/user.paths");
const productPaths = require("../modules/products/product.paths");
const rewardsPath = require("../modules/rewards/rewards.path");
const redeemsPath = require("../modules/redeems/redeems.path");
const verification = require("../middlewares/jwtVerification");
const transactionsPath = require("../modules/transactions/transactions.path");
const roleRoutes = require("../modules/roles/role.routes");
const rolePaths = require("../modules/roles/role.paths");
const kycRoutes = require("../modules/kyc/kyc.routes");
const kycPaths = require("../modules/kyc/kyc.paths");
const loyaltyRoutes = require("../modules/loyalty/loyalty.routes");
const loyaltyPaths = require("../modules/loyalty/loyalty.paths");
const campaignsRoutes = require("../modules/campaigns/campaigns.routes");
const campaignsPaths = require("../modules/campaigns/campaigns.paths");
const giftPaths = require("../modules/gift/gift.paths");
const giftRoutes = require("../modules/gift/gift.routes");
const documentRoutes = require("../modules/document/document.routes");
const documentPaths = require("../modules/document/document.paths");
const filesPaths = require("../modules/files/files.paths");
const filesRoutes = require("../modules/files/files.routes");
const ruleSetPaths = require("../modules/rule-set/rule-set.paths");
const ruleSetRoutes = require("../modules/rule-set/rule-set.routes");
const referralRoutes = require("../modules/referral/referral.routes");
const referralPaths = require("../modules/referral/referral.paths");
const videoPaths = require("../modules/videos/video.paths");
const videoRoutes = require("../modules/videos/video.routes");
const contentPaths = require("../modules/content/content.paths");
const contentRoutes = require("../modules/content/content.routes");

const globalRoutes = express.Router();

globalRoutes.use(appPaths.root, appRoutes);
globalRoutes.use(commonPaths.root, commonRoutes);
globalRoutes.use(userPaths.root, userRoutes);
globalRoutes.use(adminPaths.root, adminRoutes);
globalRoutes.use(productPaths.root, productRoutes);
globalRoutes.use(rewardsPath.root, verification.verifyAdmin, rewardRoutes);
globalRoutes.use(redeemsPath.root, redeemRoutes);
globalRoutes.use(transactionsPath.root, transactionRoutes);
globalRoutes.use(rolePaths.root, roleRoutes);
globalRoutes.use(kycPaths.root, kycRoutes);
globalRoutes.use(loyaltyPaths.root, loyaltyRoutes);
globalRoutes.use(campaignsPaths.root, campaignsRoutes);
globalRoutes.use(giftPaths.root, giftRoutes);
globalRoutes.use(documentPaths.root, documentRoutes);
globalRoutes.use(filesPaths.root, filesRoutes);
globalRoutes.use(ruleSetPaths.root, ruleSetRoutes);
globalRoutes.use(referralPaths.root, referralRoutes);
globalRoutes.use(videoPaths.root, videoRoutes);
globalRoutes.use(contentPaths.root, contentRoutes);

module.exports = globalRoutes;
