module.exports = {
  root: "/rewards",
  list: "/list",
  listGrouped: "/list-grouped",
  batches: "/batches",
  batchDetails: "/batches/:batchId",
  batchRewards: "/batches/:batchId/rewards",
  batchDeactivate: "/batches/:batchId/deactivate",
  batchUpdateById: "/batches/:batchId",
  batchDelete: "/batches/:batchId",
  batchDownload: "/batches/:batchId/download",
  batchDownloadStatus: "/batches/download-jobs/:jobId",
  batchDownloadCancel: "/batches/download-jobs/:jobId/cancel",
  create: "/create",
  delete: "/delete/:rewardId",
  update: "/update/:rewardId",
  bulkUpdate: "/bulk-update",
  batchUpdate: "/batch-update",
  details: "/details/:rewardId",
  deleteAll: "/delete",
};
