const AUDIT_LOG_ACTIONS = {
  // User Actions
  PHONE_NUMBER_CHANGE: "PHONE_NUMBER_CHANGE",

  // Season and Loyalty Config Actions
  SEASON_CREATED: "SEASON_CREATED",
  SEASON_UPDATED: "SEASON_UPDATED",
  SEASON_ACTIVATED: "SEASON_ACTIVATED",
  SEASON_DEACTIVATED: "SEASON_DEACTIVATED",
  SEASON_DELETED: "SEASON_DELETED",
  TIER_CONFIG_CREATED: "TIER_CONFIG_CREATED",
  TIER_CONFIG_UPDATED: "TIER_CONFIG_UPDATED",
  TIER_CONFIG_DELETED: "TIER_CONFIG_DELETED",
};

module.exports = {
  AUDIT_LOG_ACTIONS,
};
