const ContentPlacement = Object.freeze({
  HOME_TOP_CAROUSEL: "HOME_TOP_CAROUSEL",
  HOME_MIDDLE_BANNER: "HOME_MIDDLE_BANNER",
  HOME_BOTTOM_BANNER: "HOME_BOTTOM_BANNER",
  REWARDS_PAGE: "REWARDS_PAGE",
  PRODUCT_SELECTOR: "PRODUCT_SELECTOR",
  COVERAGE_CALCULATOR: "COVERAGE_CALCULATOR",
  GIFT_CATALOGUE: "GIFT_CATALOGUE",
  PROFILE: "PROFILE",
  SCAN_PAGE: "SCAN_PAGE",
  REWARD_SUCCESS_SCREEN: "REWARD_SUCCESS_SCREEN",
  SEASON_LANDING_PAGE: "SEASON_LANDING_PAGE",
  ANNOUNCEMENTS: "ANNOUNCEMENTS",
  SEASON_CAMPAIGN: "SEASON_CAMPAIGN",
  HOME_ANNOUNCEMENT_FEED: "HOME_ANNOUNCEMENT_FEED",
  HOME_OPENING: "HOME_OPENING",
  REWARDS_OPENING: "REWARDS_OPENING",
  SCAN_OPENING: "SCAN_OPENING",
  PROFILE_OPENING: "PROFILE_OPENING",
  SEASON_LANDING_OPENING: "SEASON_LANDING_OPENING",
  PRODUCT_SELECTOR_OPENING: "PRODUCT_SELECTOR_OPENING",
});

const ContentType = Object.freeze({
  BANNER: "BANNER",
  ANNOUNCEMENT: "ANNOUNCEMENT",
  CAMPAIGN: "CAMPAIGN",
  POPUP: "POPUP",
  INFORMATION_CARD: "INFORMATION_CARD",
});

const ContentAction = Object.freeze({
  OPEN_PRODUCT: "OPEN_PRODUCT",
  OPEN_CATEGORY: "OPEN_CATEGORY",
  OPEN_REWARDS: "OPEN_REWARDS",
  OPEN_PRODUCT_SELECTOR: "OPEN_PRODUCT_SELECTOR",
  OPEN_COVERAGE_CALCULATOR: "OPEN_COVERAGE_CALCULATOR",
  OPEN_SCAN: "OPEN_SCAN",
  OPEN_EXTERNAL_URL: "OPEN_EXTERNAL_URL",
  OPEN_INTERNAL_PAGE: "OPEN_INTERNAL_PAGE",
  OPEN_CAMPAIGN_DETAILS: "OPEN_CAMPAIGN_DETAILS",
  OPEN_BOTTOM_SHEET: "OPEN_BOTTOM_SHEET",
  OPEN_POPUP_MODAL: "OPEN_POPUP_MODAL",
  DO_NOTHING: "DO_NOTHING",
});

const PopupType = Object.freeze({
  FULLSCREEN: "FULLSCREEN",
  BOTTOM_SHEET: "BOTTOM_SHEET",
  MODAL_POPUP: "MODAL_POPUP",
  ANNOUNCEMENT_CARD: "ANNOUNCEMENT_CARD",
  BANNER: "BANNER",
});

const ContentFrequency = Object.freeze({
  ONCE: "ONCE",
  SESSION: "SESSION",
  EVERYTIME: "EVERYTIME",
});

const ALLOWED_PLACEMENTS = Object.values(ContentPlacement);
const ALLOWED_TYPES = Object.values(ContentType);
const ALLOWED_ACTIONS = Object.values(ContentAction);
const ALLOWED_POPUP_TYPES = Object.values(PopupType);
const ALLOWED_FREQUENCIES = Object.values(ContentFrequency);

module.exports = {
  ContentPlacement,
  ALLOWED_PLACEMENTS,
  ContentType,
  ALLOWED_TYPES,
  ContentAction,
  ALLOWED_ACTIONS,
  PopupType,
  ALLOWED_POPUP_TYPES,
  ContentFrequency,
  ALLOWED_FREQUENCIES,
};
