const LOYALTY_TRANSACTION_TYPES = {
  QUALIFICATION: "QUALIFICATION",
  REDEEMABLE: "REDEEMABLE",
  BOTH: "BOTH",
};

const LOYALTY_TRANSACTION_SOURCES = {
  QR_SCAN: "QR_SCAN",
  CAMPAIGN_BONUS: "CAMPAIGN_BONUS",
  WITHDRAW: "WITHDRAW",
  ADMIN_ADJUSTMENT: "ADMIN_ADJUSTMENT",
  SEASON_ROLLOVER: "SEASON_ROLLOVER",
  SCRATCH_CARD_BONUS: "SCRATCH_CARD_BONUS",
  TIER_RANK_UP: "TIER_RANK_UP",
};

const CARRY_FORWARD_BEHAVIOR = {
  RESET: "RESET",
  FULL: "FULL",
  PERCENTAGE: "PERCENTAGE",
};

module.exports = {
  LOYALTY_TRANSACTION_TYPES,
  LOYALTY_TRANSACTION_SOURCES,
  CARRY_FORWARD_BEHAVIOR,
};
