const POINTS_TRANSACTION_TYPE = {
  CREDIT: "CREDIT",
  DEBIT: "DEBIT",
};

const POINTS_TRANSACTION_REASON = {
  QR_SCAN: "QR_SCAN",
  SCRATCH_CARD_REWARD: "SCRATCH_CARD_REWARD",
  CONTEST_WIN: "CONTEST_WIN",
  WITHDRAWAL_TO_COIN: "WITHDRAWAL_TO_COIN",
  WITHDRAWAL_TO_CASH: "WITHDRAWAL_TO_CASH",
  TIER_RANK_UP_REWARD: "TIER_RANK_UP_REWARD",
  ADMIN_ADJUSTMENT: "ADMIN_ADJUSTMENT",
  REFERRAL_REWARD: "REFERRAL_REWARD",
  REFUND: "REFUND",
  MANUAL_REDEEM: "MANUAL_REDEEM",
  CAMPAIGN_BONUS: "CAMPAIGN_BONUS",
  SEASON_ROLLOVER: "SEASON_ROLLOVER",
};

module.exports = {
  POINTS_TRANSACTION_TYPE,
  POINTS_TRANSACTION_REASON,
};
