const ServiceRequestType = {
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  SIMPLE_OTP_LOGIN: "SIMPLE_OTP_LOGIN",
  CHANGE_PHONE_OLD_OTP: "CHANGE_PHONE_OLD_OTP",
  CHANGE_PHONE_OLD_VERIFIED: "CHANGE_PHONE_OLD_VERIFIED",
  CHANGE_PHONE_NEW_OTP: "CHANGE_PHONE_NEW_OTP",
};

const ServiceRequestStatus = {
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  EXPIRED: "EXPIRED",
  USED: "USED",
};

module.exports = { ServiceRequestStatus, ServiceRequestType };
