const PAYMENT_METHODS = {
    UPI: "UPI",
    NET_BANKING: 'NET_BANKING',
    DIRECT_TRANSFER:"DIRECT_TRANSFER"
}

const PAYMENT_STATUS = {
    INITIATED: "INITIATED",
    FAILED: "FAILED",
    PAID: "PAID",
    CANCELLED: "CANCELLED"
}
 const SORT_OPTIONS ={
    MOST_RECENT :'MOST_RECENT',
    AMOUNT:'AMOUNT'
 }

module.exports = { PAYMENT_STATUS, PAYMENT_METHODS, SORT_OPTIONS }