const PAYMENT_METHODS = {
    UPI: "UPI",
    NET_BANKING: 'NET_BANKING'
}

const PAYMENT_STATUS = {
    INITIATED: "INITIATED",
    PROCESSING: "PROCESSING",
    FAILED: "FAILED",
    SUCCESS: "SUCCESS"
}

module.exports = { PAYMENT_STATUS, PAYMENT_METHODS }