module.exports = {
  root: "/user",
  details: "/details",
  adminDetails: "/admin-details/:id",
  list: "/list",
  roles: "/roles",
  onboardingRoles: "/onboarding/roles",
  updateProfile: "/profile/update",
  profilePhoto: "/profile/photo",
  flagUser: "/flag/:id",
  updatePreferences: "/preference/update",
  fcmToken: "/fcm-token",
  phone: {
    verifyOldNumber: "/phone/verify-old-number",
    verifyNewNumber: "/phone/verify-new-number",
  },
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    verifyEmail: "/auth/verify-email",
    verifyOtp: "/auth/verify-otp",
    resetPassword: "/auth/reset-password",
    authenticateWithProvider: "/auth/external-provider",
    simpleLoginWithOtp: "/auth/simple-login-with-otp",
  },
  bank: {
    details: "/bank-details",
    create: "/bank-details/create",
    update: "/bank-details/update",
    delete: "/bank-details/delete",
  },
};
